server:
  port:
    8081

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: mypassword
  
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: sisdbmain

user:
  rabbitmq:
    queue: user
