server:
  port:
    8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sisdbmain

user:
  rabbitmq:
    queue: user

eureka:
  instance:
    hostname:
      localhost
    port:
      9999
  client:
    registerWithEureka:
      true
    fetchRegistry:
      false
    serviceUrl:
      defaultZone:
        http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty:
      3000

